package br.ucsal.AtvJdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Atv1 {
	public static void main(String[] args) {
		String url = "jdbc:hsqldb:mem:.";
		String user="SA";
		String pass="";
		Connection conexao = null;
		
		try {
			conexao = DriverManager.getConnection(url, user, pass);
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		
		try {
			Statement stmt = conexao.createStatement();
			
			stmt.execute("create table alunos(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,"					
					+ "matricula varchar(20) not null,"
					+ "nome varchar(50) not null)");
			
			int linhasAlteradas = stmt.executeUpdate( "INSERT INTO alunos (matricula,nome) " 
								+"VALUES ('200520010','Bruno'),"
										+"('200620011','Joaldo'),"
										+"('200720012','Renato'),"
										+"('200520013','Yla'),"
										+"('200620014','Marcos'),"
										+"('200720015','joão'),"
										+"('200520016','Maria'),"
										+"('200420017','Carlos')");
			
			ResultSet cursor = stmt.executeQuery("SELECT "
					+"matricula, nome FROM alunos WHERE matricula "
					+"like '2005%'");
			
			while(cursor.next()) {
				System.out.println("Nome: " + cursor.getString("nome"));
				System.out.println("Matricula: " + cursor.getString("matricula")+"\n");
			}
			
			cursor.close();
			stmt.close();
			conexao.close();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
}
